steps:
- name: gcr.io/vocal-booth-378619/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - 'gs://${_GCS_BUCKET}/dags'

- name: gcr.io/vocal-booth-378619/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'plugins'
    - 'gs://${_GCS_BUCKET}/plugins'

options:
  logging: CLOUD_LOGGING_ONLY

    